prose-im/prose-pod-api

ADRs/2023-12-18-a-describe-with-openapi.md
ADRs/README.md

ADR: Describe Prose Pod API using the OpenAPI Specification

---

ADRs/2023-12-18-b-auto-detect-openapi-routes.md
ADRs/README.md

ADR: Automatically detect OpenAPI routes

---

ADRs/2024-01-11-a-write-tests-in-gherkin.md
ADRs/README.md

ADR: Write tests with the Gherkin syntax

---

Cargo.lock
Dockerfile
entity/Cargo.toml
entity/src/model/mod.rs
src/main.rs
src/v1/invitations/routes.rs

I fixed a few things I noticed after submitting my last PRs and I forgot to cherry-pick them before merging 🙄
I advise you to check commit by commit, it will be easier to understand.

fix: Various fixes

---

Cargo.lock
Cargo.toml
Makefile
service/src/services/live_xmpp_service/live_xmpp_service.rs
service/src/services/xmpp_service.rs
tests/prelude/mock_xmpp_service.rs
tests/v1/members/mod.rs

chore(deps): Bump dependencies

---

Cargo.lock
Cargo.toml
service/src/prosody/prosody_rest.rs
service/src/services/live_xmpp_service/live_xmpp_service.rs
service/src/services/xmpp_service.rs
src/error.rs
src/guards/jwt.rs
tests/behavior.rs

- fix: Fix member enriching (vCard4 loading was broken)
- fix: Work around breaking change introduced in `email_address`
- fix: Fix release build (almost)
- chore: Improve logging

fix: Various hotfixes

---

.dockerignore
.gitignore
CONTRIBUTING.md
Taskfile.yaml
scripts/integration-test
scripts/open-api-docs-ui
scripts/run-locally/build-images
scripts/run-locally/init
scripts/run-locally/reset
scripts/run-locally/run
scripts/run-locally/update
scripts/util.sh
tutorials/run-locally.md

See [tutorials/run-locally.md](https://github.com/prose-im/prose-pod-api/pull/58/files#diff-b90e33355c926237f03284f5c2db9ad82bb696db446392aacf062a3e4132571e)

feat: Allow one to easily start a Prose Pod API locally

---

crates/rest-api/src/features/network_checks/check_all.rs
crates/rest-api/src/features/network_checks/mod.rs
crates/service/src/features/network_checks/network_checker.rs

This route was documented but didn't exist.

feat: Add JSON route `/v1/network/checks`

---

crates/rest-api/src/features/invitations/invitation_actions.rs
crates/rest-api/src/features/invitations/invite_member.rs
crates/rest-api/src/responders/either.rs
crates/rest-api/src/responders/mod.rs
crates/rest-api/static/api-docs/openapi.json
crates/rest-api/tests/integration/step-ci/invitations.yaml
crates/rest-api/tests/integration/step-ci/members.yaml
crates/service/src/features/invitations/invitation_controller.rs
crates/service/src/util/mod.rs

Fix: The API returns a 500 when inviting the same user twice

---

.github/workflows/release.yaml
.github/workflows/test.yaml
crates/rest-api/src/features/invitations/invite_member.rs
crates/service/src/features/auth/auth_service.rs
crates/service/src/features/invitations/invitation_controller.rs
crates/service/src/features/network_checks/models/dns.rs

fix: Fix release builds

---

Cargo.lock
crates/prosody-config/Cargo.toml
crates/prosody-config/src/model/mod.rs
crates/prosody-config/src/model/secrets.rs
crates/prosody-config/src/prosody_config/conversion.rs
crates/prosody-config/src/prosody_config/mod.rs
crates/prosody-config/src/prosody_config_file/mod.rs
crates/prosody-config/tests/prosody_config.rs
crates/rest-api/src/features/server_config/mod.rs
crates/rest-api/src/features/server_config/tls_profile.rs
crates/rest-api/static/api-docs/features/server-config.yaml
crates/rest-api/static/api-docs/openapi.yaml
crates/service/src/features/app_config/defaults.rs
crates/service/src/features/app_config/mod.rs
crates/service/src/features/prosody/prosody_config_from_db.rs
crates/service/src/features/server_config/entities/mod.rs
crates/service/src/features/server_config/entities/server_config.rs
crates/service/src/features/server_config/migrations/m20250112_122600_create_tls_profile.rs
crates/service/src/features/server_config/migrations/mod.rs
crates/service/src/features/server_config/models/server_config.rs
crates/service/src/features/xmpp/server_manager.rs
crates/service/src/migrations/mod.rs
tests/integration/step-ci/pod-config.yaml
tests/integration/step-ci/server-config.yaml

feat(server-config)!: Add 'Network encryption' configuration routes

---

crates/rest-api/src/error/errors.rs
crates/rest-api/src/features/members/guards/member_service.rs
crates/rest-api/src/features/members/mod.rs
crates/rest-api/tests/features/members.rs
crates/service/src/features/members/member_service.rs
features/members/member-delete.feature

fix: Prevent one from deleting their own account

---

Cargo.lock
Cargo.toml
crates/rest-api/src/features/auth/guards/auth_service.rs
crates/rest-api/src/features/auth/guards/auth_token.rs
crates/rest-api/src/features/auth/guards/authenticated.rs
crates/rest-api/src/features/auth/guards/basic_auth.rs
crates/rest-api/src/features/auth/guards/is_admin.rs
crates/rest-api/src/features/auth/guards/user_info.rs
crates/rest-api/src/features/init/guards/init_service.rs
crates/rest-api/src/features/invitations/guards/invitation_service.rs
crates/rest-api/src/features/invitations/mod.rs
crates/rest-api/src/features/members/guards/member_service.rs
crates/rest-api/src/features/members/guards/unauthenticated_member_service.rs
crates/rest-api/src/features/members/mod.rs
crates/rest-api/src/features/network_checks/guards/network_checker.rs
crates/rest-api/src/features/workspace_details/guards/workspace_service.rs
crates/rest-api/src/guards/app_config.rs
crates/rest-api/src/guards/notification_service.rs
crates/rest-api/src/guards/pod_network_config.rs
crates/rest-api/src/guards/secrets_store.rs
crates/rest-api/src/guards/server_config.rs
crates/rest-api/src/guards/server_ctl.rs
crates/rest-api/src/guards/server_manager.rs
crates/rest-api/src/guards/uuid_generator.rs
crates/rest-api/src/guards/xmpp_service.rs
crates/rest-api/src/util/content_type_or.rs

chore: Update `axum` to `0.8`

---

crates/rest-api/src/features/pod_config/pod_address.rs
crates/rest-api/tests/cucumber_parameters/http_status.rs
crates/rest-api/tests/features/pod_config.rs
features/pod-config/pod-address.feature

fix(pod-address): Fix socket hang up when setting pod address to an empty value

---

crates/service/src/features/prosody/prosody_oauth2.rs
tests/integration/step-ci/auth.yaml

fix(auth): Yield 401 Unauthorized when logging in with a bad JID

---

Cargo.lock
Cargo.toml
Taskfile.dist.yaml
crates/rest-api/src/features/auth/guards/auth_service.rs
crates/rest-api/src/features/auth/guards/auth_token.rs
crates/rest-api/src/features/auth/guards/authenticated.rs
crates/rest-api/src/features/auth/guards/basic_auth.rs
crates/rest-api/src/features/auth/guards/is_admin.rs
crates/rest-api/src/features/auth/guards/user_info.rs
crates/rest-api/src/features/init/guards/init_service.rs
crates/rest-api/src/features/invitations/guards/invitation_service.rs
crates/rest-api/src/features/invitations/mod.rs
crates/rest-api/src/features/members/guards/member_service.rs
crates/rest-api/src/features/members/guards/unauthenticated_member_service.rs
crates/rest-api/src/features/members/mod.rs
crates/rest-api/src/features/network_checks/guards/network_checker.rs
crates/rest-api/src/features/workspace_details/guards/workspace_service.rs
crates/rest-api/src/guards/app_config.rs
crates/rest-api/src/guards/notification_service.rs
crates/rest-api/src/guards/pod_network_config.rs
crates/rest-api/src/guards/secrets_store.rs
crates/rest-api/src/guards/server_config.rs
crates/rest-api/src/guards/server_ctl.rs
crates/rest-api/src/guards/server_manager.rs
crates/rest-api/src/guards/uuid_generator.rs
crates/rest-api/src/guards/xmpp_service.rs
crates/rest-api/src/util/content_type_or.rs

Hopefully it fixes #160 (again?).

fix(ci): Fix release builds

---

src/rest-api/src/features/startup_actions/mod.rs
src/rest-api/src/features/startup_actions/start_cron_tasks.rs
src/rest-api/src/util/lifecycle_manager.rs
src/rest-api/tests/prelude/mocks/mock_secrets_store.rs
src/service/src/features/cron/mod.rs
src/service/src/features/cron/refresh_service_accounts_tokens.rs
src/service/src/features/mod.rs
src/service/src/features/prosody/prosody_rest.rs
src/service/src/features/secrets/live_secrets_store.rs
src/service/src/features/secrets/secrets_store.rs
src/service/src/features/xmpp/server_manager.rs

fix: Refresh service accounts OAuth tokens before they expire

---

src/service/src/features/network_checks/live_network_checker.rs

fix: Fix API hangs when running network checks after 5 minutes

---

src/rest-api/tests/prelude/notifier.rs
src/service/src/features/invitations/models/workspace_invitation_notification.rs
src/service/src/features/notifications/dependencies/notifier/email.rs

Send plain text as UTF-8, and as HTML too to fix #216.

feat: Improve emails

---

Cargo.lock
Cargo.toml
src/rest-api/src/features/members/get_members.rs
src/rest-api/src/features/members/guards/member_service.rs
src/rest-api/src/forms/mod.rs
src/rest-api/src/forms/opt_query.rs
src/rest-api/src/forms/search_query.rs
src/service/Cargo.toml
src/service/src/features/members/member_repository.rs
src/service/src/features/members/member_service.rs
src/service/src/util/concurrent_task_runner.rs
src/service/src/util/mod.rs
src/service/src/util/unaccent.rs

feat(members): Allow searching for members using the `q` query parameter

---

src/rest-api/src/features/members/enrich_members.rs
src/rest-api/src/features/members/get_member.rs
src/rest-api/src/features/members/get_members.rs
src/service/src/features/members/member_repository.rs
src/service/src/features/members/member_service.rs
src/service/src/util/cache.rs
src/service/src/util/mod.rs

And a few other things.
Relates to #228.

Optimize members enriching

---

benchmarks/prosody-storage-speeds/bechmark-prosody-storage-speeds
local-run/scripts/constants.sh
local-run/scripts/run
local-run/scripts/scenarios-delete
local-run/scripts/stop

feat(local-run): Delete all ephemeral scenarios instead of just the last one in `task local:stop`

---

src/service/src/features/network_checks/live_network_checker.rs

I can’t get a useful stacktrace but I think `spawn_blocking` caused:
```log
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.43.0/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
```
<https://users.rust-lang.org/t/tonic-tokio-cannot-drop-a-runtime-in-a-context-where-blocking-is-not-allowed/116667/3> would support that.

fix(network-checks): Fix tokio panic by using hickory’s `TokioAsyncResolver`

---

README.md
src/rest-api/src/features/startup_actions/create_service_accounts.rs
src/rest-api/src/features/startup_actions/migrate_workspace_vcard.rs
src/rest-api/src/features/startup_actions/rotate_api_xmpp_password.rs
src/rest-api/src/features/startup_actions/start_cron_tasks.rs
src/rest-api/src/features/workspace_details/guards/workspace_service.rs
src/rest-api/src/guards/secrets_store.rs
src/rest-api/src/lib.rs
src/rest-api/src/main.rs
src/rest-api/src/util/lifecycle_manager.rs
src/rest-api/src/util/mod.rs
src/rest-api/tests/prelude/mocks/mock_secrets_store.rs
src/rest-api/tests/prelude/test_api.rs
src/rest-api/tests/prelude/test_world.rs
src/service/src/features/prosody/prosody_admin_rest.rs
src/service/src/features/secrets/live_secrets_store.rs
src/service/src/features/secrets/secrets_store.rs
src/service/src/features/xmpp/server_manager.rs

feat(lifecycle): Reload on `SIGHUP`

---

Taskfile.dist.yaml
scripts/release

feat(release): Update packaged license when running `task release`

---

local-run/scripts/otlp

fix(local-run): Fix `task telemetry:start` not working when Docker network changed
