- static/api-docs/openapi.json
Literally a one character diff
> chore: Remove extraneous comma in JSON

- Cargo.lock
- Cargo.toml
- service/Cargo.toml
- service/src/controllers/invitation_controller.rs
- service/src/controllers/member_controller.rs
- service/src/dependencies/any_notifier/generic.rs
- service/src/dependencies/notifier.rs
- service/src/prosody/prosody_admin_rest.rs
- service/src/prosody/prosody_oauth2.rs
- service/src/prosody/prosody_rest.rs
- service/src/services/live_xmpp_service/live_xmpp_service.rs
- service/src/services/server_manager.rs
- service/src/services/xmpp_service.rs
- src/lib.rs
- src/main.rs
- tests/behavior.rs
We're not doing real tracing yet but it'll come one day so we have no reason to use `log` while most dependencies use `tracing`.
> chore: Move from `log` to `tracing`

- service/src/controllers/member_controller.rs
- service/src/prosody/prosody_admin_rest.rs
- service/src/prosody/prosody_oauth2.rs
- service/src/services/auth_service.rs
- service/src/services/live_xmpp_service/live_xmpp_service.rs
- service/src/services/server_ctl.rs
- service/src/services/server_manager.rs
- service/src/services/user_service.rs
- service/src/services/xmpp_service.rs
- src/lib.rs
- src/v1/members/routes.rs
- src/v1/routes.rs
- tests/prelude/mock_auth_service.rs
- tests/prelude/mock_server_ctl.rs
- tests/prelude/mock_xmpp_service.rs
```rust
tokio::task::block_in_place(move || {
Handle::current().block_on(async move {
// ...
})
})
```
was used in a lot of places, potentially causing thread blocks. By using `async_trait` we make sure no such issue will arise.
> chore: Migrate dependencies to async traits

- ADRs/2024-05-27-a-lazily-enriching-member-data.md
- ADRs/2024-06-05-a-prose-xmpp-and-mod_rest-to-send-stanzas.md
- ADRs/README.md
Added 2 ADRs:
1. “ADR: Enrich member data in a separate HTTP API call”
2. “ADR: Use `prose-xmpp` and `mod_rest` to send stanzas to Prosody”
Both have already been accepted via https://github.com/prose-im/prose-pod-api/pull/19, this is a post-hoc documentation.
> ADRs: Lazy enriching and stanza sending using `mod_rest` and `prose-xmpp`

- Cargo.toml
- tests/behavior.rs
Even when steps failed, `cargo test --test behavior` would exit with code `0`… which means CI would still succeed with broken tests 😅
> fix(tests): Fix behavior tests exit code

- src/error.rs
Server errors (`500..<600`) have `ERROR` level, `Forbidden`s have `WARN` level and the rest have `INFO` level.
I also made sure errors cannot be logged twice. It did not resolve the fact that errors are logged 2 or 3 times in tests, I think there's a problem with how Cucumber and Rocket subscribe to logs and "relog" them.
> feat(error): Lower log level of most client errors (except "Forbidden"s)

- crates/api/tests/integration/.gitignore
- scripts/open-api-docs-ui
Because `prose-pod-system` does not contain a `Prose.toml` file anymore, `task open-api-docs-ui` was failing saying `Could not read config`.
It's now fixed.
I also fixed the fact that `in-memory.env` was unintentionally ignored by git.
> fix: Fix `task open-api-docs-ui`

- crates/api/src/main.rs
- crates/service/src/services/network_checker/live_network_checker.rs
The SSE routes performing DNS checks were useless because of DNS caching at different layers. When querying DNS records we now query the authoritative nameservers directly (by IP address) instead of using the recursive system-defined ones.
> fix(dns): Fix DNS caching issues

- Prose.toml
- crates/rest-api/src/error/errors.rs
- crates/rest-api/src/error/mod.rs
- crates/rest-api/src/features/auth/mod.rs
- crates/rest-api/src/features/init/init_server_config.rs
- crates/rest-api/src/features/init/init_workspace.rs
- crates/rest-api/static/api-docs/openapi.json
- crates/rest-api/tests/features/dns-setup.feature
- crates/rest-api/tests/features/pod-config/pod-address.feature
- crates/rest-api/tests/v1/init.rs
- crates/service/src/errors.rs
- crates/service/src/features/prosody/prosody_admin_rest.rs
- crates/service/src/features/prosody/prosody_oauth2.rs
- crates/service/src/features/xmpp/server_ctl.rs
- crates/service/src/lib.rs
Mainly improved how errors work. They now return a message, an optional payload and optional recovery suggestions in debug builds. Example:
```json
{
"reason": "internal_server_error"
}
```
now becomes
```json
{
"error": "internal_server_error",
"message": "auth_service::Error: `ProsodyOAuth2` error: Unexpected API response: invalid JID",
"debug_info": {
"message": "invalid JID",
"request": {
"body": "grant_type=password&username=dev.admin%40test.org&password=&scope=xmpp",
"headers": [
"authorization: Basic ZGV2LmFkbWluQHRlc3Qub3JnOg==",
"content-type: application/x-www-form-urlencoded"
],
"url": "http://prose-pod-server:5280/oauth2/token"
},
"response": {
"body": {
"error": "invalid_request",
"error_description": "invalid JID"
},
"headers": [
"cache-control: no-store",
"connection: …
```
> chore: Improve how errors are returned in debug builds

- .github/workflows/test.yml
- crates/rest-api/tests/integration/in-memory.env
- scripts/integration-test
- Do not run GitHub Action twice in PRs (used to run because of both `push` and `pull_request` events)
- Update `RUST_LOG` in integration tests (make it less verbose)
- Run integration tests in GitHub Action (fixes #73)
- Use `dtolnay/rust-toolchain` instead of the unmaintained `actions-rs/toolchain` (fixes #82)
> https://github.com/actions-rs/toolchain has been archived since Oct 13, 2023, which means it will not get security patches.
>
> David Tolnay ([@dtolnay](https://github.com/dtolnay)) is a big contributor in the Rust ecosystem, which can reassure us that this action will be maintained and vulnerability-free (at least more than an action from a shady user account).
> Also the entire action code is less than 200 lines of understandable YAML and Bash, compared to [the 1.3MB JS script …
> Improve CI

- CONTRIBUTING.md
- Taskfile.yaml
- crates/rest-api/tests/integration/compose/compose.yaml
- scripts/build-image
- scripts/constants.sh
- scripts/integration-test
- scripts/open-api-docs-ui
- scripts/run-locally/build-images
- scripts/run-locally/init
- scripts/run-locally/run
- scripts/run-locally/update
- tutorials/run-locally.md
- `task local-run` runs the latest released images (from [Docker Hub](https://hub.docker.com/r/proseim/prose-pod-api/tags))
- Therefore, no more minutes-long local builds and no need to `task local-update` anymore
- You can get the latest unreleased patches by running `task local-run -- --api=edge`
- You don't need to have the `prose-pod-server` repository locally anymore
- `task open-api-docs-ui` uses the latest released images too (can be overridden with the same options as `task local-run`)
- `task build-image` accepts `--tag=DOCKER_TAG` to override the default `local` tag
- `task integration-test` accepts `--server=DOCKER_TAG` to override the image that will run (e.g. to use the locally built one instead of the latest release)
- And various improvements to documentation & logs
- `task …
> chore: Run locally using tagged images instead of forcing local builds

- crates/migration/src/lib.rs
- crates/migration/src/m20231221_172027_create_server_config.rs
- crates/migration/src/m20241214_134500_add_push_notif_config.rs
- crates/rest-api/src/features/server_config/mod.rs
- crates/rest-api/src/features/server_config/push_notifications.rs
- crates/rest-api/static/api-docs/openapi.json
- crates/service/src/features/app_config/defaults.rs
- crates/service/src/features/app_config/mod.rs
- crates/service/src/features/prosody/prosody_config_from_db.rs
- crates/service/src/features/server_config/entities/server_config.rs
- crates/service/src/features/server_config/models/server_config.rs
- crates/service/src/features/xmpp/server_manager.rs
- crates/service/tests/prosody/snapshots/behavior__prosody__default_config.snap
- crates/service/tests/prosody/snapshots/behavior__prosody__minimal_config.snap
- 5 new routes:
- `PUT /v1/server/config/push-notifications/reset`
- `PUT /v1/server/config/push-notification-with-body/reset`
- `PUT /v1/server/config/push-notification-with-body`
- `PUT /v1/server/config/push-notification-with-sender/reset`
- `PUT /v1/server/config/push-notification-with-sender`
- 2 new fields in `ServerConfig`:
```diff
"required": [
...
+   "push_notification_with_body",
+   "push_notification_with_sender"
],
```
> Add support for XEP-0357: Push Notifications

- .dockerignore
- .github/workflows/release.yaml
- Dockerfile
- scripts/build-image
Speeds up local & CI builds using `cargo-chef`, reorganizing the Dockerfile and ignoring more file paths.
For example, rebuilding the image after changing `openapi.json` takes a few seconds instead of minutes (~5).
> Speed up builds

- crates/service/src/features/app_config/defaults.rs
- crates/service/src/features/app_config/mod.rs
- local-run/scenarios/default/Prose.toml
Simplifies `Prose.toml` configuration files.
> feat: Add a default value for `databases.main.url`

- .github/workflows/release.yaml
- .github/workflows/test.yaml
- CONTRIBUTING.md
- Cargo.toml
- local-run/scripts/build-images
- scripts/build-image
I tried different cargo profile configurations, and I came up with better settings to speed up all builds. I also created a `staging` profile which we will now use when building `edge`. It should be about 2 times quicker now.
Fixes #104.
Here are my benchmarks (not a source of truth, more like notes for myself):
```toml
[profile.release]
opt-level = "s"
lto = true
debug = false
debug-assertions = false
panic = "abort"
```
594.97 real         4.13 user         5.82 sys
27.7MB
---
```toml
[profile.release]
opt-level = "s"
lto = "thin"
debug = false
debug-assertions = false
panic = "abort"
```
605.31 real         4.33 user         5.13 sys
34.1MB
---
```toml
[profile.release]
opt-level = 2
lto = "thin"
debug = false
debug-assertions = false
panic = "abort"
```
675.15 real         4.72 user …
> chore(ci): Speed up `edge` build

- crates/rest-api/src/error/mod.rs
- crates/rest-api/src/features/startup_actions/mod.rs
- crates/rest-api/src/main.rs
- crates/service/src/features/app_config/defaults.rs
- crates/service/src/features/app_config/mod.rs
- local-run/scenarios/default/Prose.toml
- With `debug_use_at_your_own_risk.log_config_at_startup = true`, the API will log the app configuration at startup
- While passwords are not printed, some data could be considered sensitive which is why it's "use at your own risk"
- With `debug_use_at_your_own_risk.detailed_error_responses = true`, the API returns
```txt
{
"error": self.code,
"message": self.message,
"debug_info": self.debug_info,
}
```
instead of just
```txt
{
"error": self.code
}
```
- This should not be enabled in production as it leaks too much information about internal errors
> feat: Allow returning detailed error responses in non-debug builds

- Cargo.lock
- Cargo.toml
- crates/rest-api/src/features/auth/guards/auth_service.rs
- crates/rest-api/src/features/auth/guards/auth_token.rs
- crates/rest-api/src/features/auth/guards/authenticated.rs
- crates/rest-api/src/features/auth/guards/basic_auth.rs
- crates/rest-api/src/features/auth/guards/is_admin.rs
- crates/rest-api/src/features/auth/guards/user_info.rs
- crates/rest-api/src/features/init/guards/init_service.rs
- crates/rest-api/src/features/invitations/guards/invitation_service.rs
- crates/rest-api/src/features/invitations/mod.rs
- crates/rest-api/src/features/members/guards/member_service.rs
- crates/rest-api/src/features/members/guards/unauthenticated_member_service.rs
- crates/rest-api/src/features/members/mod.rs
- crates/rest-api/src/features/network_checks/guards/network_checker.rs
- crates/rest-api/src/features/workspace_details/guards/workspace_service.rs
- crates/rest-api/src/guards/app_config.rs
- crates/rest-api/src/guards/notification_service.rs
- crates/rest-api/src/guards/pod_network_config.rs
- crates/rest-api/src/guards/secrets_store.rs
- crates/rest-api/src/guards/server_config.rs
- crates/rest-api/src/guards/server_ctl.rs
- crates/rest-api/src/guards/server_manager.rs
- crates/rest-api/src/guards/uuid_generator.rs
- crates/rest-api/src/guards/xmpp_service.rs
- crates/rest-api/src/util/content_type_or.rs
Release builds have been broken since this commit. amd64 builds work (integration tests pass), but arm64 builds fail because of a segmentation fault 🤨 Let's just revert, we didn't **need** the bump. Hopefully next time we try bumping the issue will have been fixed.
(I haven't submitted a bug report, I don't have time for it right now.)
This reverts commit 36458aa961ed41fb31ffdaf27bab37b30871f24a.
Reopens #115.
Fixes #160.
> Revert "chore: Update `axum` to `0.8`"

- Dockerfile
- scripts/build-image
> feat(build): Stop using `cargo-chef`

- crates/rest-api/src/features/auth/guards/user_info.rs
- crates/service/src/features/app_config/defaults.rs
- crates/service/src/features/app_config/mod.rs
- crates/service/src/features/prosody/prosody_config_from_db.rs
- crates/service/src/features/prosody/prosody_rest.rs
- crates/service/src/features/xmpp/xmpp_service.rs
- features/members/members-list.feature
- local-run/scripts/constants.sh
- scripts/integration-test
- tests/integration/Prose-tokens-expired.toml
- tests/integration/step-ci/auth-expired.yaml
> fix(auth): Return `401`s when tokens expire (not `403s`)

- crates/rest-api/src/features/init/init_server_config.rs
- crates/rest-api/src/features/init/init_workspace.rs
- crates/rest-api/static/api-docs/features/dns-setup.yaml
- crates/rest-api/static/api-docs/features/init.yaml
- crates/rest-api/static/api-docs/features/invitations.yaml
- crates/rest-api/static/api-docs/features/pod-config.yaml
- crates/rest-api/static/api-docs/features/server-config.yaml
- crates/rest-api/tests/cucumber_parameters/http_status.rs
- crates/rest-api/tests/features/init.rs
- features/dns-setup.feature
We don't support caching yet, but `400` wasn't semantically correct. One day we will require `If-None-Match: *` on the affected routes. One thing at a time.
NOTE: This is ground work for the next commit regarding #174.
> feat!: Use status code `412` instead of `400` when things are not initialized

- README.md
- crates/rest-api/src/error/errors.rs
- crates/rest-api/src/features/server_config/get_server_config.rs
- crates/rest-api/src/features/server_config/mod.rs
- crates/rest-api/static/api-docs/features/server-config.yaml
- crates/rest-api/static/api-docs/openapi.yaml
- crates/rest-api/static/api-docs/shared.yaml
- crates/rest-api/tests/cucumber_parameters/http_status.rs
- crates/service/src/features/server_config/server_config_repository.rs
- tests/integration/step-ci/init.yaml
Fixes #174.
Answering `412` without a precondition in the request would have been incorrect, therefore the route requires `If-None-Match: *` to work properly. Otherwise, it returns `428`.
When we will support caching, we will remove the `If-None-Match: *` requirement, but for now it's the correct way to do it.
Since it's a `HEAD` request there is no response body with error details, which is why using status codes semantically was a requirement here.
> feat: Add `HEAD /v1/server/config`

- Cargo.lock
- Cargo.toml
- src/service/src/features/workspace/models/workspace.rs
Hey!
In order to match the recommended behavior described in https://xmpp.org/extensions/xep-0292.html#apps, I've set the `kind` of the workspace vCard to `application`.
Edit: Just noticed that you added an `org` kind already.
> Set Workspace vCard kind to ‘application’

- src/rest-api/src/features/init/init_server_config.rs
- src/rest-api/src/features/startup_actions/add_workspace_to_team.rs
- src/rest-api/src/features/startup_actions/mod.rs
- src/service/src/features/init/init_service.rs
Users need to receive PEP events when the workspace vCard changes for Prose to update the UI automatically. For this, the Workspace needs to be in their rosters. By adding the Workspace to the team, it will automatically be added to everyone’s rosters.
> feat: Add Workspace XMPP account to everyone’s rosters

- .github/workflows/release.yaml
- .github/workflows/test.yaml
Hello @RemiBardon :wave: 
I'm opened this PR to resolve #93
In this PR, I modified the following
I added a dependency on the test workflow using the `workflow_run` directive, as described in the [Stack Overflow article](https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions/64733705#64733705) you referenced in the issue.
I also added the condition `github.event.workflow_run.conclusion == 'success'` to the `create-github-release` and `ship-docker-image jobs`. According to this [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run), there are three activity types for `workflow_run`: **completed**, **requested**, and **in_progress**. If I understand correctly, the …
> Create release after tests pass #93

- .github/workflows/test.yaml
Hello @RemiBardon :wave:
I've opened this PR to resolve #106 
As discussed in the issue, i have added a new job called `check-no-unwanted-strings` to the Lint & Test workflow.
This job searches through all `.feature` files in the repository and flags any lines containing the unwanted tags `@testing` or `@debug`.
As you suggested, this check uses `grep` commands, and **it will exit the workflow if any unwanted tags are found**.
I’ve also updated the `smoke-test` job dependencies to include this new job.
Let me know if any adjustments are needed! :smiley:
> Make sure no `@testing` or `@debug` is committed in feature files

- .zed/settings.json
- Cargo.lock
- docs/openapi/features/onboarding.yaml
- docs/openapi/openapi.yaml
- features/network-checks/dns-record-checks.feature
- features/onboarding.feature
- src/rest-api/Cargo.toml
- src/rest-api/src/features/startup_actions/mod.rs
- src/rest-api/src/util/lifecycle_manager.rs
- src/rest-api/tests/cucumber_parameters/boolean.rs
- src/rest-api/tests/cucumber_parameters/mod.rs
- src/rest-api/tests/features/mod.rs
- src/rest-api/tests/features/network_checks.rs
- src/rest-api/tests/features/onboarding.rs
- src/rest-api/tests/prelude/mocks/mock_network_checker.rs
- src/rest-api/tests/prelude/test_api.rs
- src/service/src/features/global_storage/kv_store.rs
See #242.
This also fixes the fact that the API couldn’t update values inserted in the global key/value store… which means onboarding routes didn’t work properly.
> Onboarding docs and tests

- src/rest-api/src/features/startup_actions/mod.rs
- src/service/src/features/app_config/mod.rs
- tests/integration/prose-tokens-expired.toml
Renames `debug_only.skip_startup_actions` to `debug_use_at_your_own_risk.skip_startup_actions`.
NOTE: Needs to be available in release builds so we can run the CI in `prose-pod-system` without having to start live notifiers.
> chore(app-config)!: Make `skip_startup_actions` available in release builds

- local-run/scripts/constants.sh
- src/rest-api/src/features/startup_actions/backfill_database.rs
- src/rest-api/src/features/startup_actions/mod.rs
- src/rest-api/tests/prelude/mocks/mock_server_ctl.rs
- src/service/src/features/members/member_repository.rs
- src/service/src/features/members/unauthenticated_member_service.rs
- src/service/src/features/prosody/mod.rs
- src/service/src/features/prosody/prosody_admin_rest.rs
- src/service/src/features/xmpp/live_server_ctl.rs
- src/service/src/features/xmpp/server_ctl.rs
Load XMPP users at startup. If ones are not in the Pod API database, create them. If there are open invitations for them, read the email address then delete the invitation.
This improves the migration UX.
> feat: Load XMPP users at startup
